from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
    path("timeline/", views.timeline_view, name="timeline"),
    path("calendar/", views.calendar_view, name="calendar"),
    path("assets/", views.asset_list_view, name="asset_list"),
    path("assets/new/", views.asset_create_view, name="asset_create"),
    path("assets/<int:asset_id>/edit/", views.asset_edit_view, name="asset_edit"),
    path("assets/<int:asset_id>/delete/", views.asset_delete_view, name="asset_delete"),
    path("engines/", views.engine_list_view, name="engine_list"),
    path("engines/new/", views.engine_create_view, name="engine_create"),
    path("engines/<int:engine_id>/edit/", views.engine_edit_view, name="engine_edit"),
    path("engines/<int:engine_id>/delete/", views.engine_delete_view, name="engine_delete"),
    path("io-devices/<int:io_id>/edit/", views.io_device_edit_view, name="io_device_edit"),
    path("io-devices/<int:io_id>/delete/", views.io_device_delete_view, name="io_device_delete"),
    path("kits/", views.kit_list_view, name="kit_list"),
    path("kits/new/", views.kit_create_view, name="kit_create"),
    path("kits/<int:kit_id>/edit/", views.kit_edit_view, name="kit_edit"),
    path("kits/<int:kit_id>/pdf/", views.kit_pdf_view, name="kit_pdf"),
    path("kits/<int:kit_id>/delete/", views.kit_delete_view, name="kit_delete"),
    path("kits/<int:kit_id>/set-status/", views.kit_set_status_view, name="kit_set_status"),
    path("kits/<int:kit_id>/booking-info/", views.kit_booking_info_view, name="kit_booking_info"),
    path("jobs/<int:job_id>/edit/", views.job_edit_view, name="job_edit"),
    path("licenses/", views.license_list_view, name="license_list"),
    path("licenses/new/", views.license_create_view, name="license_create"),
    path("licenses/<int:license_id>/edit/", views.license_edit_view, name="license_edit"),
    path("licenses/<int:license_id>/delete/", views.license_delete_view, name="license_delete"),
    path("vans/", views.van_list_view, name="van_list"),
    path("vans/new/", views.van_create_view, name="van_create"),
    path("vans/<int:vehicle_id>/", views.van_detail_view, name="van_detail"),
    path("vans/<int:vehicle_id>/edit/", views.van_edit_view, name="van_edit"),
    path("vans/<int:vehicle_id>/delete/", views.van_delete_view, name="van_delete"),
    path("vans/<int:vehicle_id>/usage/add/", views.van_usage_add, name="van_usage_add"),
    path("vans/<int:vehicle_id>/maintenance/add/", views.van_maintenance_add, name="van_maintenance_add"),
    path("vans/<int:vehicle_id>/checklist/add/", views.van_checklist_add, name="van_checklist_add"),
    path("vans/usage/<int:log_id>/delete/", views.van_usage_delete, name="van_usage_delete"),
    path("vans/maintenance/<int:log_id>/delete/", views.van_maintenance_delete, name="van_maintenance_delete"),
    path("vans/checklist/<int:checklist_id>/delete/", views.van_checklist_delete, name="van_checklist_delete"),
    path("report-issue/", views.ticket_report_view, name="ticket_report"),
    path("tickets/", views.ticket_list_view, name="ticket_list"),
    path("tickets/<int:ticket_id>/", views.ticket_detail_view, name="ticket_detail"),
    path("tickets/<int:ticket_id>/delete/", views.ticket_delete_view, name="ticket_delete"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/export/", views.export_csv_view, name="export_csv"),
    path("settings/tags/add/", views.settings_tag_add, name="settings_tag_add"),
    path("settings/tags/<int:tag_id>/delete/", views.settings_tag_delete, name="settings_tag_delete"),
    path("settings/functionalities/add/", views.settings_functionality_add, name="settings_functionality_add"),
    path(
        "settings/functionalities/<int:func_id>/delete/",
        views.settings_functionality_delete,
        name="settings_functionality_delete",
    ),
    path("api/kits/<int:kit_id>/", views.kit_detail_api, name="kit_detail_api"),
    path("api/jobs/<int:job_id>/", views.job_detail_api, name="job_detail_api"),
    path("api/jobs/<int:job_id>/delete/", views.delete_job, name="delete_job"),
    path("api/jobs/<int:job_id>/clone/", views.clone_job, name="clone_job"),
    path("api/jobs/create/", views.job_create_view, name="job_create"),
    path("api/bookings/create/", views.create_booking, name="create_booking"),
    path("api/bookings/<int:booking_id>/delete/", views.delete_booking, name="delete_booking"),
    path("api/staff-bookings/create/", views.create_staff_booking, name="create_staff_booking"),
    path(
        "api/staff-bookings/<int:booking_id>/delete/",
        views.delete_staff_booking,
        name="delete_staff_booking",
    ),
    path("api/license-bookings/create/", views.create_license_booking, name="create_license_booking"),
    path(
        "api/license-bookings/<int:booking_id>/delete/",
        views.delete_license_booking,
        name="delete_license_booking",
    ),
    path("stocktake/", views.stocktake_index_view, name="stocktake_index"),
    path("stocktake/new/", views.stocktake_new_view, name="stocktake_new"),
    path("stocktake/stale/", views.stocktake_stale_view, name="stocktake_stale"),
    path("stocktake/<int:session_id>/", views.stocktake_detail_view, name="stocktake_detail"),
    path("stocktake/<int:session_id>/close/", views.stocktake_close_view, name="stocktake_close"),
    path("stocktake/<int:session_id>/delete/", views.stocktake_delete_view, name="stocktake_delete"),
    path("stocktake/<int:session_id>/pdf/", views.stocktake_pdf_view, name="stocktake_pdf"),
    path("stocktake/<int:session_id>/entries/<int:entry_id>/review/", views.stocktake_review_entry, name="stocktake_review_entry"),
]
