from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
    path("timeline/", views.timeline_view, name="timeline"),
    path("calendar/", views.calendar_view, name="calendar"),
    path("assets/", views.asset_list_view, name="asset_list"),
    path("engines/", views.engine_list_view, name="engine_list"),
    path("engines/new/", views.engine_create_view, name="engine_create"),
    path("engines/<int:engine_id>/edit/", views.engine_edit_view, name="engine_edit"),
    path("engines/<int:engine_id>/delete/", views.engine_delete_view, name="engine_delete"),
    path("kits/", views.kit_list_view, name="kit_list"),
    path("kits/new/", views.kit_create_view, name="kit_create"),
    path("kits/<int:kit_id>/edit/", views.kit_edit_view, name="kit_edit"),
    path("kits/<int:kit_id>/pdf/", views.kit_pdf_view, name="kit_pdf"),
    path("kits/<int:kit_id>/delete/", views.kit_delete_view, name="kit_delete"),
    path("licenses/", views.license_list_view, name="license_list"),
    path("vans/", views.van_list_view, name="van_list"),
    path("vans/new/", views.van_create_view, name="van_create"),
    path("vans/<int:vehicle_id>/", views.van_detail_view, name="van_detail"),
    path("vans/<int:vehicle_id>/edit/", views.van_edit_view, name="van_edit"),
    path("vans/<int:vehicle_id>/delete/", views.van_delete_view, name="van_delete"),
    path("vans/<int:vehicle_id>/usage/add/", views.van_usage_add, name="van_usage_add"),
    path("vans/<int:vehicle_id>/maintenance/add/", views.van_maintenance_add, name="van_maintenance_add"),
    path("vans/<int:vehicle_id>/checklist/add/", views.van_checklist_add, name="van_checklist_add"),
    path("vans/usage/<int:log_id>/delete/", views.van_usage_delete, name="van_usage_delete"),
    path("vans/maintenance/<int:log_id>/delete/", views.van_maintenance_delete, name="van_maintenance_delete"),
    path("vans/checklist/<int:checklist_id>/delete/", views.van_checklist_delete, name="van_checklist_delete"),
    path("report-issue/", views.ticket_report_view, name="ticket_report"),
    path("tickets/", views.ticket_list_view, name="ticket_list"),
    path("tickets/<int:ticket_id>/", views.ticket_detail_view, name="ticket_detail"),
    path("tickets/<int:ticket_id>/delete/", views.ticket_delete_view, name="ticket_delete"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/export/", views.export_csv_view, name="export_csv"),
    path("api/kits/<int:kit_id>/", views.kit_detail_api, name="kit_detail_api"),
    path("api/jobs/<int:job_id>/", views.job_detail_api, name="job_detail_api"),
    path("api/jobs/<int:job_id>/delete/", views.delete_job, name="delete_job"),
    path("api/jobs/<int:job_id>/clone/", views.clone_job, name="clone_job"),
    path("api/jobs/create/", views.job_create_view, name="job_create"),
    path("api/bookings/create/", views.create_booking, name="create_booking"),
    path("api/bookings/<int:booking_id>/delete/", views.delete_booking, name="delete_booking"),
    path("api/staff-bookings/create/", views.create_staff_booking, name="create_staff_booking"),
    path(
        "api/staff-bookings/<int:booking_id>/delete/",
        views.delete_staff_booking,
        name="delete_staff_booking",
    ),
    path("api/license-bookings/create/", views.create_license_booking, name="create_license_booking"),
    path(
        "api/license-bookings/<int:booking_id>/delete/",
        views.delete_license_booking,
        name="delete_license_booking",
    ),
]
