# Generated by Django 6.0.7 on 2026-07-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PREP', 'Prep'), ('RIG', 'Rig'), ('TX', 'TX'), ('WAREHOUSE', 'Warehouse'), ('TECH_DEVELOPMENT', 'Tech development')], max_length=20, unique=True)),
                ('color', models.CharField(default='#EAB308', max_length=7)),
            ],
            options={
                'verbose_name': 'Category color',
                'verbose_name_plural': 'Category colors',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PREP', 'Prep'), ('RIG', 'Rig'), ('TX', 'TX'), ('WAREHOUSE', 'Warehouse'), ('TECH_DEVELOPMENT', 'Tech development')], default='TX', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('custom_color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck instead of deleting once someone leaves, to keep their booking history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=64, unique=True)),
                ('asset_type', models.CharField(choices=[('ENGINE', 'Engine'), ('COMPONENT', 'Component'), ('STANDALONE', 'Standalone'), ('PERIPHERAL', 'Peripheral'), ('CABLE', 'Cable'), ('IO_DEVICE', 'I/O Device'), ('LICENSE', 'License')], max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=120)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('NEEDS_REPAIR', 'Needs repair'), ('MAINTENANCE', 'Maintenance'), ('MISSING', 'Missing')], default='AVAILABLE', max_length=20)),
                ('archived', models.BooleanField(default=False, help_text='Archived assets are hidden from availability and pickers, but kept for booking history. Use this instead of deleting.')),
                ('notes', models.TextField(blank=True)),
                ('license_type', models.CharField(blank=True, max_length=60)),
                ('license_functionality', models.CharField(blank=True, max_length=200)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_engine', models.ForeignKey(blank=True, help_text='The Engine this item is physically installed in, if any.', limit_choices_to={'asset_type': 'ENGINE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_assets', to='inventory.asset')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to='inventory.staffmember')),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, help_text='Direct members of this kit - Engines and/or loose assets (including Licenses). Components nested inside a member Engine travel with it automatically and do not need to be added here separately.', related_name='kits', to='inventory.asset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('functionalities', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_bookings', to='inventory.asset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bookings', to='inventory.job')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('job', 'asset', 'start_date', 'end_date'), name='unique_asset_booking_per_job_window')],
            },
        ),
        migrations.CreateModel(
            name='KitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_bookings', to='inventory.job')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.kit')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('job', 'kit', 'start_date', 'end_date'), name='unique_kit_booking_per_job_window')],
            },
        ),
        migrations.CreateModel(
            name='StaffBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_bookings', to='inventory.job')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.staffmember')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('job', 'staff_member', 'start_date', 'end_date'), name='unique_staff_booking_per_job_window')],
            },
        ),
    ]
