# Generated by Django 6.0.7 on 2026-07-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ticket_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_updated_notes',
            field=models.CharField(blank=True, help_text="Short note on what changed, e.g. 'Replaced fan, retested OK'.", max_length=300),
        ),
    ]
