# Generated by Django 5.2.16 on 2026-07-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_vehicle_vanusagelog_vanmaintenancelog_vanchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License functionality',
                'verbose_name_plural': 'License functionalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(blank=True, help_text='Optional hex color, e.g. #EAB308.', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='license_duration_end',
            field=models.DateField(blank=True, help_text="License only. End of the overall period this license is usable/active for (the 'Duration' / expiry shown on the timeline). Within this window it can still be assigned to different jobs for shorter stretches.", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='license_duration_start',
            field=models.DateField(blank=True, help_text='License only. Start of the overall period this license is usable/active for.', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ENGINE', 'Engine'), ('SONNET', 'Sonnet Box'), ('COMPONENT', 'Component'), ('STANDALONE', 'Standalone'), ('PERIPHERAL', 'Peripheral'), ('CABLE', 'Cable'), ('IO_DEVICE', 'I/O Device'), ('LICENSE', 'License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='license_functionality',
            field=models.CharField(blank=True, help_text="Deprecated free-text field, kept for old data. Use 'functionalities' instead.", max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='license_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('NETWORK', 'Network'), ('DONGLE', 'Dongle'), ('SOFTWARE', 'Software')], help_text='License only. Tick one: Permanent, Network, Dongle, or Software.', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent_engine',
            field=models.ForeignKey(blank=True, help_text='The Engine or Sonnet Box this item is physically installed in, if any.', limit_choices_to={'asset_type__in': ('ENGINE', 'SONNET')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_assets', to='inventory.asset'),
        ),
        migrations.CreateModel(
            name='KitAssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_asset_tags', to='inventory.asset')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_asset_tags', to='inventory.kit')),
                ('tag', models.ForeignKey(blank=True, help_text='Optional label for what this asset is used for in this kit, e.g. MAIN.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_asset_tags', to='inventory.tag')),
            ],
            options={
                'ordering': ['kit', 'asset__asset_id'],
            },
        ),
        migrations.RemoveField(
            model_name='kit',
            name='assets',
        ),
        migrations.AddField(
            model_name='kit',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Direct members of this kit - Engines and/or loose assets (including Licenses). Components nested inside a member Engine (or a Sonnet Box nested in one) travel with it automatically and do not need to be added here separately.', related_name='kits', through='inventory.KitAssetTag', to='inventory.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='functionalities',
            field=models.ManyToManyField(blank=True, help_text='License only. Tick every functionality this license unlocks (e.g. SDI Out, Unreal Render Blade, Viz).', related_name='licenses', to='inventory.licensefunctionality'),
        ),
        migrations.AddConstraint(
            model_name='kitassettag',
            constraint=models.UniqueConstraint(fields=('kit', 'asset'), name='unique_asset_per_kit'),
        ),
    ]
