# Generated by Django 5.2.16 on 2026-07-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_seed_tags_and_functionalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='viz_ticket',
            field=models.CharField(blank=True, help_text='License only. The Viz ticket number/reference that authorized the current Duration.', max_length=120),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent_engine',
            field=models.ForeignKey(blank=True, help_text='The Engine or Sonnet Box this item is physically installed in, if any.', limit_choices_to={'asset_type__in': ('ENGINE', 'SONNET', 'IO_DEVICE')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_assets', to='inventory.asset'),
        ),
    ]
