# Generated by Django 5.2.16 on 2026-07-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_asset_viz_ticket_alter_asset_parent_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['name'], 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Kit tag', 'verbose_name_plural': 'Kit tags'},
        ),
    ]
