# Generated by Django 5.2.16 on 2026-07-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_vanmaintenancelog_logged_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycolor',
            options={'ordering': ['category'], 'verbose_name': 'Category colour', 'verbose_name_plural': 'Category colours'},
        ),
        migrations.AlterModelOptions(
            name='licensefunctionality',
            options={'ordering': ['name'], 'verbose_name': 'License Functionality', 'verbose_name_plural': 'License Functionalities'},
        ),
    ]
