# New AssetHistory table for the Engine/License "history" panel (right-hand
# side of the edit forms) - one row per logged change: scalar field changes
# (status, archived, qty, asset_id, and License-only fields), component
# nesting changes on Engines/I-O Devices, License functionality changes, a
# "created" entry, and manual notes (only when the note text actually
# changes, not every save - see AssetHistory.record_note's docstring).
#
# changed_by links to StaffMember (not the Django login) to stay consistent
# with the existing "Last updated by" picker, which allows logging an
# update on someone else's behalf.
#
# The AlterField on Kit.assets is unrelated and harmless - it's just
# picking up a help_text wording change from the earlier Sonnet Box
# cleanup that was never actually migrated before now (help_text is
# tracked by makemigrations even though it has no real schema effect).
#
# Verified against a real PostgreSQL database: created assets, ran the
# create/edit flows that trigger AssetHistory.record_* end to end, confirmed
# entries were created with correct old/new values and correct StaffMember
# attribution, confirmed the filtered_for() week/month/all windows and
# pagination behave correctly, then ran this migration backward to confirm
# the table drops cleanly.
# Generated by Django 5.2.16 on 2026-07-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_staffmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Direct members of this kit - Engines and/or loose assets (including Licenses). Components nested inside a member Engine (or an I/O Device nested in one) travel with it automatically and do not need to be added here separately.', related_name='kits', through='inventory.KitAssetTag', to='inventory.asset'),
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(help_text="e.g. 'status', 'qty', 'component_added', 'note', 'created'.", max_length=40)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.asset')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.staffmember')),
            ],
            options={
                'verbose_name_plural': 'Asset history',
                'ordering': ['-created_at'],
            },
        ),
    ]
