# Generated by Django 5.2.16 on 2026-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_asset_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ENGINE', 'Engine'), ('COMPONENT', 'Component'), ('STANDALONE', 'Standalone'), ('PERIPHERAL', 'Peripheral'), ('CABLE', 'Cable'), ('IO_DEVICE', 'I/O Device'), ('LICENSE', 'License'), ('LAPTOP', 'Laptop')], max_length=20),
        ),
    ]
