# Generated by Django 5.2.16 on 2026-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_laptop_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitassettag',
            options={'ordering': ['kit', 'created_at']},
        ),
        migrations.AddField(
            model_name='kitassettag',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text="How many units of this asset this kit uses. Only meaningful for bulk/stock assets (Asset.qty > 1, e.g. a 'Wired Mouse' row representing several identical units) - individually-tracked assets (Engines, Components, etc.) are always 1."),
        ),
    ]
