# Generated by Django 5.2.16 on 2026-07-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_kitassettag_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(help_text="e.g. 'name', 'note', 'asset_added', 'asset_removed', 'quantity_changed', 'created'.", max_length=40)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.staffmember')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.kit')),
            ],
            options={
                'verbose_name_plural': 'Kit history',
                'ordering': ['-created_at'],
            },
        ),
    ]
