# Generated by Django 5.2.16 on 2026-07-29 20:39

from django.db import migrations, models


def recompute_existing_statuses(apps, schema_editor):
    """One-off correction on deploy: bring every existing asset's status
    in line with actual kit membership/nesting/bookings, same logic the
    signals will maintain going forward. Uses the real status_sync module
    (not the historical apps.get_model snapshot) since the computation
    logic itself isn't part of the schema being migrated.

    Skipped on an empty database (fresh installs): the live status_sync
    code references columns added by later migrations (e.g. Kit.status),
    and with no assets there is nothing to correct anyway."""
    Asset = apps.get_model("inventory", "Asset")
    if not Asset.objects.exists():
        return
    from inventory.status_sync import recompute_all
    recompute_all()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_kit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('BOOKED', 'Booked'), ('NEEDS_REPAIR', 'Needs repair'), ('MAINTENANCE', 'Maintenance'), ('MISSING', 'Missing')], default='AVAILABLE', max_length=20),
        ),
        migrations.RunPython(recompute_existing_statuses, migrations.RunPython.noop),
    ]
