# Generated by Django 5.2.16 on 2026-07-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_booked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycolour',
            name='category',
            field=models.CharField(choices=[('PREP', 'Prep'), ('RIG', 'Rig'), ('TX', 'TX'), ('WAREHOUSE', 'Warehouse'), ('TECH_DEVELOPMENT', 'Tech development'), ('PERMANENT_INSTALL', 'Permanent Install'), ('LONG_TERM_LOAN', 'Long Term Loan')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('PREP', 'Prep'), ('RIG', 'Rig'), ('TX', 'TX'), ('WAREHOUSE', 'Warehouse'), ('TECH_DEVELOPMENT', 'Tech development'), ('PERMANENT_INSTALL', 'Permanent Install'), ('LONG_TERM_LOAN', 'Long Term Loan')], default='TX', max_length=20),
        ),
    ]
