# Generated by Django 5.2.17 on 2026-08-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_kitassettag_tag_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional name for this session, e.g. 'August warehouse check'.", max_length=120)),
                ('asset_types', models.JSONField(default=list, help_text="List of AssetType values included in this session, e.g. ['PERIPHERAL', 'CABLE'].")),
                ('staleness_days', models.PositiveIntegerField(blank=True, help_text='Only include assets not updated in this many days. Null = all assets.', null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to='inventory.staffmember')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FLAGGED', 'Flagged'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('last_updated_snapshot', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_entries', to='inventory.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_reviews', to='inventory.staffmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.stocktakesession')),
            ],
            options={
                'ordering': ['asset__last_updated_date', 'asset__asset_id'],
                'unique_together': {('session', 'asset')},
            },
        ),
    ]
