# Generated by Django 5.2.17 on 2026-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_stocktake_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_photos/'),
        ),
    ]
